INSERT INTO Account (username, password) VALUES ('imallinson', 'password')
INSERT INTO ShoppingList (account_username) VALUES ('imallinson')
INSERT INTO Meal (date, mealTime, servings, username) VALUES ('20190130', DINNER, 1, 'imallinson')
INSERT INTO Recipe (isPublic, recipeName, servings, username, mealID) VALUES (true, 'Burgers', 1, 'imallinson', 1)
INSERT INTO Ingredient (ingredientName, amount, measure, recipeID) VALUES ('beef mince', 250, g, 1)
INSERT INTO Ingredient (ingredientName, amount, measure, recipeID) VALUES ('egg', 1, , 1)
INSERT INTO Ingredient (ingredientName, amount, measure, recipeID) VALUES ('onion', 0.5, , 1)
INSERT INTO Ingredient (ingredientName, amount, measure, recipeID) VALUES ('dried oregano', 1, tsp, 1)
INSERT INTO Ingredient (ingredientName, amount, measure, recipeID) VALUES ('bread crumbs', 50, g, 1)